# Installs my spotifyd frontend
- name: Spotifyd frontend dependencies
  apt: name={{ packages }} state=present
  tags: apt
  become: yes
  vars:
    packages:
      - feh
      - i3
      - xinit
      - lxterminal
- name: Clone current track repository
  git:
    repo: https://github.com/thepont/spotifyd-current-track
    dest: /home/{{ admin_user }}/git/spotifyd-current-track
