# Installs my spotifyd frontend
- name: Spotifyd frontend dependencies
  apt: name={{ packages }} state=present
  tags: apt
  become: yes
  vars:
    packages:
      - feh
      - i3
      - xinit
      - compton
      - lxterminal
      - unclutter
      - x11-xserver-utils
# - name: Install current track global NPM
#   become: yes
# #   become_user: root
#   command: npm install -g git+https://github.com/thepont/spotifyd-current-track
#   npm:
#     global: true
#     name: git+https://github.com/thepont/spotifyd-current-track
- name: Clone current track repository
  git:
    repo: https://github.com/thepont/spotifyd-current-track
    dest: /home/{{ admin_user }}/git/spotifyd-current-track
- name: install spotifyd current track deps
  command: npm install
  args:
    chdir: /home/{{ admin_user }}/git/spotifyd-current-track
- name: "Startx on tty1 login"
  lineinfile:
    insertafter: "EOF"
    state: "present"
    path: "/home/{{ admin_user }}/.bashrc"
    line: "if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then exec startx; fi"
- name: "i3 default wm"
  copy:
    content: "exec /usr/bin/i3"
    dest: "/home/{{ admin_user }}/.xinitrc"
- name: "lxterminal setup"
  block:
    - file: 
        path: "/home/{{ admin_user }}/.config/lxterminal" 
        state: directory
    - copy:
        src: "../config/lxterminal.conf"
        dest: "/home/{{ admin_user }}/.config/lxterminal/lxterminal.conf"
- name: "i3 setup"
  block:
    - file: 
        path: "/home/{{ admin_user }}/.config/i3" 
        state: directory
    - copy:
        src: "../config/i3"
        dest: "/home/{{ admin_user }}/.config/i3/config"
    # - copy:
    #     src: "../config/i3-saved-state.json"
    #     dest: "/home/{{ admin_user }}/.config/i3/i3-saved-state.json"
- name: "Compton Setup"
  copy:
    src: "../config/compton.conf"
    dest: "/home/{{ admin_user }}/.config/compton.conf"
- name: "Export spotify client id"
  lineinfile:
    insertafter: "EOF"
    state: "present"
    path: "/home/{{ admin_user }}/.bashrc"
    line: "export SPOTIFY_CLIENT_ID={{spotify_client_id}}"
- name: "Export spotify client secret"
  lineinfile:
    insertafter: "EOF"
    state: "present"
    path: "/home/{{ admin_user }}/.bashrc"
    line: "export SPOTIFY_CLIENT_SECRET={{spotify_client_secret}}"
