- hosts: spottypi
  remote_user: "{{ admin_user }}"
  become: yes
  vars:
    admin_user: pont
  tasks:
    - name: Install spotifyd binary.
      unarchive:
        src: https://github.com/Spotifyd/spotifyd/releases/download/0.2.12/spotifyd-{{ spotifyd_version }}-armv6-slim.zip
        dest: /usr/bin/
        remote_src: yes
        mode: 777
    - name: Download service file.
      get_url:
        url: https://raw.githubusercontent.com/Spotifyd/spotifyd/master/contrib/spotifyd.service
        dest: /etc/systemd/user/spotifyd.service
    - name: enable service httpd and ensure it is not masked
      systemd:
        name: spotifyd
        enabled: yes
        scope: user
        masked: no
    - name: Copy spotifyd config.
      copy:
        src: ./conf/spotifyd.conf
        dest: /home/{{ admin_user }}/spotifyd.conf