
#
# Installs Spotifyd.
#
- name: Install spotifyd binary.
  become: yes
  unarchive:
    src: https://github.com/Spotifyd/spotifyd/releases/download/v0.2.4/spotifyd-2019-01-28-armv6.zip
    dest: /usr/bin/
    remote_src: yes
    mode: 777
- name: Download service file.
  get_url:
    url: https://raw.githubusercontent.com/Spotifyd/spotifyd/master/contrib/spotifyd.service
    dest: /etc/systemd/user/spotifyd.service
- name: Copy spotifyd config.
  copy:
    src: ../config/spotifyd.conf
    dest: /home/{{ admin_user }}/.config/spotifyd.conf
