  - name: Configure the hostname
    become: yes
    block:
      - replace:
          dest: "/etc/hosts"
          regexp: "raspberrypi"
          replace: "spottypi"
      - hostname:
          name: "spottypi"